//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TokoBeDia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeaderTransactions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HeaderTransactions()
        {
            this.DetailTransactions = new HashSet<DetailTransactions>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
        public int PaymentTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailTransactions> DetailTransactions { get; set; }
        public virtual Users Users { get; set; }
        public virtual PaymentTypes PaymentTypes { get; set; }
    }
}
